version: '3.9'

services:
  vite-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vite-app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: ["npm", "run", "dev", "--", "--host"]
